/*
 * generated by Xtext
 */
package de.cau.cs.kieler.sccharts.ui;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SCChartsUiModule /* extends SCTXActivator */{
    
    public static final String PLUGIN_ID = "de.cau.cs.kieler.sccharts.ui";

//    /**
//     * {@inheritDoc}
//     */
//    @Override
//    public void start(BundleContext context) throws Exception {
//        super.start(context);
//        
//        // FIXME magic registration
//        SCChartsDiagramHighlighter.create();
//        SCChartsDiagramLiveValues.create();
//    } //$NON-NLS-1$
//    
    
}
