/*
 * generated by Xtext 2.13.0
 */
package de.cau.cs.kieler.kexpressions.kext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class KExtRuntimeModule extends AbstractKExtRuntimeModule {
}
