/*
 * generated by Xtext 2.13.0
 */
package de.cau.cs.kieler.kexpressions.kext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KExtStandaloneSetup extends KExtStandaloneSetupGenerated {

	def static void doSetup() {
		new KExtStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
