/*
 * generated by Xtext 2.13.0
 */
package de.cau.cs.kieler.sccharts.text


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SCTXStandaloneSetup extends SCTXStandaloneSetupGenerated {

	def static void doSetup() {
		new SCTXStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
