/*
 * generated by Xtext 2.13.0
 */
package de.cau.cs.kieler.annotations.ide


/**
 * Use this class to register ide components.
 */
class AnnotationsIdeModule extends AbstractAnnotationsIdeModule {
}
