/*
 * generated by Xtext 2.14.0
 */
package de.scheidtbachmann.statemachine


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StateMachineStandaloneSetup extends StateMachineStandaloneSetupGenerated {

	def static void doSetup() {
		new StateMachineStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
