/*
 * generated by Xtext 2.13.0
 */
package de.cau.cs.kieler.kexpressions.keffects.ide


/**
 * Use this class to register ide components.
 */
class KEffectsIdeModule extends AbstractKEffectsIdeModule {
}
