/*
 * generated by Xtext 2.13.0
 */
package de.cau.cs.kieler.annotations


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AnnotationsStandaloneSetup extends AnnotationsStandaloneSetupGenerated {

	def static void doSetup() {
		new AnnotationsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
