/*
 * generated by Xtext 2.13.0
 */
package de.cau.cs.kieler.kexpressions.keffects


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KEffectsStandaloneSetup extends KEffectsStandaloneSetupGenerated {

	def static void doSetup() {
		new KEffectsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
