/*
 * generated by Xtext 2.14.0
 */
package de.scheidtbachmann.statemachine.ide


/**
 * Use this class to register ide components.
 */
class StateMachineIdeModule extends AbstractStateMachineIdeModule {
}
