/*
 * generated by Xtext 2.13.0
 */
package de.cau.cs.kieler.kexpressions


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class KExpressionsRuntimeModule extends AbstractKExpressionsRuntimeModule {
}
