/*
 * generated by Xtext 2.13.0
 */
package de.cau.cs.kieler.kexpressions


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KExpressionsStandaloneSetup extends KExpressionsStandaloneSetupGenerated {

	def static void doSetup() {
		new KExpressionsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
